- name: Manage Kibana Dataview
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Manage Kibana Dataview
      WildDogOne.elasticsearch_kibana.elasticsearch_kibana_data_view:
        state: present
        force: yes
        kb_url: http://localhost:5601
        kb_user: admin
        kb_pass: password
        dv_name: test_data_view
        dv_title: logs-test-*
        dv_timeFieldName: "@timestamp"
